### ISSUE TITLE
Undefined method `each` in convert_string_to_bool

### ISSUE THREAD

**Issue by ShimShtein** [fog/fog-ovirt#62]
While creating a host from template with Foreman I am getting:

```
2019-03-17T17:15:49 [W|app|1ff89b4b] »Failed to create a compute oris ovirt4 (oVirt) instance shim-eldon-ganong.dummy: undefined method `each' for nil:NilClass
 |  «
 | NoMethodError: undefined method `each' for nil:NilClass
 | /usr/local/rvm/gems/ruby-2.4.1@foreman/gems/fog-ovirt-1.1.6/lib/fog/ovirt/compute/v4.rb:114:in `convert_string_to_bool'
 | /usr/local/rvm/gems/ruby-2.4.1@foreman/gems/fog-ovirt-1.1.6/lib/fog/ovirt/compute/v4.rb:122:in `block (2 levels) in convert_string_to_bool'
 | /usr/local/rvm/gems/ruby-2.4.1@foreman/gems/fog-ovirt-1.1.6/lib/fog/ovirt/compute/v4.rb:122:in `map'
 | /usr/local/rvm/gems/ruby-2.4.1@foreman/gems/fog-ovirt-1.1.6/lib/fog/ovirt/compute/v4.rb:122:in `block in convert_string_to_bool'
 | /usr/local/rvm/gems/ruby-2.4.1@foreman/gems/fog-ovirt-1.1.6/lib/fog/ovirt/compute/v4.rb:114:in `each'
 | /usr/local/rvm/gems/ruby-2.4.1@foreman/gems/fog-ovirt-1.1.6/lib/fog/ovirt/compute/v4.rb:114:in `convert_string_to_bool'
 | /usr/local/rvm/gems/ruby-2.4.1@foreman/gems/fog-ovirt-1.1.6/lib/fog/ovirt/requests/compute/v4/create_vm.rb:27:in `create_vm'
 | /usr/local/rvm/gems/ruby-2.4.1@foreman/gems/fog-ovirt-1.1.6/lib/fog/ovirt/models/compute/server.rb:179:in `save'
 | /usr/local/rvm/gems/ruby-2.4.1@foreman/gems/fog-core-1.45.0/lib/fog/core/collection.rb:50:in `create'
 | /home/shim/Documents/foreman/foreman/app/models/compute_resource.rb:195:in `create_vm'
 | /home/shim/Documents/foreman/foreman/app/models/compute_resources/foreman/model/ovirt.rb:282:in `create_vm'
```

**Comment by shiramax** [comment]
@ShimShtein which template did you used? I can't reproduce it

**Comment by sander1988** [comment]
Hi,

There is still another bug in the convert_string_to_bool function. It doesn't validate the data type of the item in value.map (when it's an array). It caused the same error. It happens when deploying a host to oVirt (from Foreman 1.23):

```
NoMethodError: undefined method `each' for #<Fog::Ovirt::Compute::Interface:0x007f0b76120628>
/usr/share/foreman/vendor/ruby/2.3.0/gems/fog-ovirt-1.2.1/lib/fog/ovirt/compute/v4.rb:116:in `convert_string_to_bool'
/usr/share/foreman/vendor/ruby/2.3.0/gems/fog-ovirt-1.2.1/lib/fog/ovirt/compute/v4.rb:124:in `block (2 levels) in convert_string_to_bool'
/usr/share/foreman/vendor/ruby/2.3.0/gems/fog-core-2.1.0/lib/fog/core/collection.rb:18:in `map'
/usr/share/foreman/vendor/ruby/2.3.0/gems/fog-core-2.1.0/lib/fog/core/collection.rb:18:in `map'
/usr/share/foreman/vendor/ruby/2.3.0/gems/fog-ovirt-1.2.1/lib/fog/ovirt/compute/v4.rb:124:in `block in convert_string_to_bool'
/usr/share/foreman/vendor/ruby/2.3.0/gems/fog-ovirt-1.2.1/lib/fog/ovirt/compute/v4.rb:116:in `each'
/usr/share/foreman/vendor/ruby/2.3.0/gems/fog-ovirt-1.2.1/lib/fog/ovirt/compute/v4.rb:116:in `convert_string_to_bool'
/usr/share/foreman/vendor/ruby/2.3.0/gems/fog-ovirt-1.2.1/lib/fog/ovirt/requests/compute/v4/update_vm.rb:9:in `update_vm'
/usr/share/foreman/vendor/ruby/2.3.0/gems/fog-ovirt-1.2.1/lib/fog/ovirt/models/compute/server.rb:177:in `save'
/usr/share/foreman/app/models/compute_resources/foreman/model/ovirt.rb:242:in `start_vm'
```

I have created this fix; it hope it helps:
```
def convert_string_to_bool(opts)
  return opts unless opts.present?
  opts.each do |key, value|
    if value.is_a? Hash
      convert_string_to_bool(value)
    elsif value.is_a? Array
      convert_string_to_bool_array(value)
    else
      opts[key] = convert_string_to_bool_item(value)
    end
  end
  opts
end

def convert_string_to_bool_array(value)
  value.map! { |item|
    if item.is_a? Hash
      convert_string_to_bool(item)
    elsif item.is_a? Array
      convert_string_to_bool_array(item)
    else
      item = convert_string_to_bool_item(item)
    end
  }
end 

def convert_string_to_bool_item(value)
  if value == "true"
    return true
  end
  if value == "false"
    return false
  end
  return value
end
```

**Comment by shiramax** [comment]
thanks @sander1988! , would you like to open a PR ? or should I do it for you?

**Comment by bagasse** [comment]
Maybe `value.downcase == "true"` and `value.downcase == "false"` should be a nice addition ?

**Comment by shiramax** [comment]
fixed the issue in: https://github.com/fog/fog-ovirt/pull/77
