### ISSUE TITLE
Error When i try to run the app  syntax error, unexpected ',' (SyntaxError) ...e_search_by_datacenter(search:, datacenter:, page: nil)

### ISSUE THREAD

**Issue by mariohmol** [fog/fog-ovirt#64]
Hi.

i have an up where runs the bundle install , but when i run via `rails s` i get this error

Any ideas?

```
MacBook-Pro-de-Gil:app user$ rails s
/Users/user/.rvm/gems/ruby-2.0.0-p451/gems/activesupport-4.0.1/lib/active_support/dependencies.rb:229:in `require': /Users/user/.rvm/gems/ruby-2.0.0-p451/gems/fog-ovirt-1.1.6/lib/fog/ovirt/compute/v4.rb:193: syntax error, unexpected ',' (SyntaxError)
...e_search_by_datacenter(search:, datacenter:, page: nil)
...                               ^
/Users/user/.rvm/gems/ruby-2.0.0-p451/gems/fog-ovirt-1.1.6/lib/fog/ovirt/compute/v4.rb:207: syntax error, unexpected keyword_end, expecting end-of-input
	from /Users/user/.rvm/gems/ruby-2.0.0-p451/gems/activesupport-4.0.1/lib/active_support/dependencies.rb:229:in `block in require'
	from /Users/user/.rvm/gems/ruby-2.0.0-p451/gems/activesupport-4.0.1/lib/active_support/dependencies.rb:214:in `load_dependency'
	from /Users/user/.rvm/gems/ruby-2.0.0-p451/gems/activesupport-4.0.1/lib/active_support/dependencies.rb:229:in `require'
	from /Users/user/.rvm/gems/ruby-2.0.0-p451/gems/fog-ovirt-1.1.6/lib/fog/ovirt/compute.rb:54:in `<class:Ovirt>'
	from /Users/user/.rvm/gems/ruby-2.0.0-p451/gems/fog-ovirt-1.1.6/lib/fog/ovirt/compute.rb:3:in `<module:Compute>'
	from /Users/user/.rvm/gems/ruby-2.0.0-p451/gems/fog-ovirt-1.1.6/lib/fog/ovirt/compute.rb:2:in `<module:Fog>'
	from /Users/user/.rvm/gems/ruby-2.0.0-p451/gems/fog-ovirt-1.1.6/lib/fog/ovirt/compute.rb:1:in `<top (required)>'
	from /Users/user/.rvm/gems/ruby-2.0.0-p451/gems/activesupport-4.0.1/lib/active_support/dependencies.rb:229:in `require'
	from /Users/user/.rvm/gems/ruby-2.0.0-p451/gems/activesupport-4.0.1/lib/active_support/dependencies.rb:229:in `block in require'
	from /Users/user/.rvm/gems/ruby-2.0.0-p451/gems/activesupport-4.0.1/lib/active_support/dependencies.rb:214:in `load_dependency'
	from /Users/user/.rvm/gems/ruby-2.0.0-p451/gems/activesupport-4.0.1/lib/active_support/dependencies.rb:229:in `require'
	from /Users/user/.rvm/gems/ruby-2.0.0-p451/gems/fog-2.0.0/lib/fog/ovirt.rb:1:in `<top (required)>'
	from /Users/user/.rvm/gems/ruby-2.0.0-p451/gems/activesupport-4.0.1/lib/active_support/dependencies.rb:229:in `require'
	from /Users/user/.rvm/gems/ruby-2.0.0-p451/gems/activesupport-4.0.1/lib/active_support/dependencies.rb:229:in `block in require'
	from /Users/user/.rvm/gems/ruby-2.0.0-p451/gems/activesupport-4.0.1/lib/active_support/dependencies.rb:214:in `load_dependency'
	from /Users/user/.rvm/gems/ruby-2.0.0-p451/gems/activesupport-4.0.1/lib/active_support/dependencies.rb:229:in `require'
	from /Users/user/.rvm/gems/ruby-2.0.0-p451/gems/fog-2.0.0/lib/fog.rb:48:in `<top (required)>'
	from /Users/user/.rvm/gems/ruby-2.0.0-p451/gems/bundler-1.17.3/lib/bundler/runtime.rb:81:in `require'
	from /Users/user/.rvm/gems/ruby-2.0.0-p451/gems/bundler-1.17.3/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
	from /Users/user/.rvm/gems/ruby-2.0.0-p451/gems/bundler-1.17.3/lib/bundler/runtime.rb:76:in `each'
	from /Users/user/.rvm/gems/ruby-2.0.0-p451/gems/bundler-1.17.3/lib/bundler/runtime.rb:76:in `block in require'
	from /Users/user/.rvm/gems/ruby-2.0.0-p451/gems/bundler-1.17.3/lib/bundler/runtime.rb:65:in `each'
	from /Users/user/.rvm/gems/ruby-2.0.0-p451/gems/bundler-1.17.3/lib/bundler/runtime.rb:65:in `require'
	from /Users/user/.rvm/gems/ruby-2.0.0-p451/gems/bundler-1.17.3/lib/bundler.rb:114:in `require'
	from /Users/user/Documents/Application/myapp/app/config/application.rb:13:in `<top (required)>'
	from /Users/user/.rvm/gems/ruby-2.0.0-p451/gems/railties-4.0.1/lib/rails/commands.rb:74:in `require'
	from /Users/user/.rvm/gems/ruby-2.0.0-p451/gems/railties-4.0.1/lib/rails/commands.rb:74:in `block in <top (required)>'
	from /Users/user/.rvm/gems/ruby-2.0.0-p451/gems/railties-4.0.1/lib/rails/commands.rb:71:in `tap'
	from /Users/user/.rvm/gems/ruby-2.0.0-p451/gems/railties-4.0.1/lib/rails/commands.rb:71:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'

```

**Comment by mariohmol** [comment]
If you guys could make a fast look and think this fixes.. please publish this. will help our dev team
